<?php 
	define('POST_TITLE','Başlık');
	define('FRIENDFEED_ID','Friendfeed ID');
	define('FF_COMMENTS','Yorumlar');
	define('USERNAME_APIKEY_MSG','Sistemi kullanabilmek için friendfeed kullanıcı adınızı ve remote key\'inizi girmelisiniz. <a href="http://friendfeed.com/account/api" target="_blank">Buradan</a> öğrenebilirsiniz.');
	define('OPTIONS','Ayarlar');
	define('FF_USERNAME','FriendFeed Kullanıcı Adınız');
	define('FF_REMOTE_KEY','FriendFeed Remote Key\'iniz');
	define('FF_DATA_SAVED_MSG','Ayarlarınız Kayıt Edildi');
	define('FF_ITEM_DELETED_SUCCESS','FriendFeed Ögesi Başarı ile Silindi');
	define('FF_ITEM_DELETED_FAIL','FriendFeed Ögesi Silinemedi');
	define('FF_ITEMS_NOT_FOUND','Blogunuz üzerinden FriendFeed\'e kayıt edilmiş öge bulunmuyor. Eklentiyi yüklediğiniz tarihten itibaren blogunuza yazmış olduğunuz içerikler FriendFeed\'e link olarak eklenecektir.');
	define('LIKED_MSG','bu yazıyı FriendFeed üzerinde sevdi.');
	define('SINGLE_LIKED_MSG','bu yazıyı FriendFeed üzerinde sevdi.');
	define('COMMENTS_FOR_POST_IN_FF','Yazısı için FriendFeed Üzerinde Yapılan Yorumlar');
	define('COMMENT','Yorum');
	define('COMMENT_ID','ID');
	define('COMMENT_AUTHOR','Yorum Yazarı');
	define('COMMENT_PROFILE','Yorum Yazarı URL');
	define('COMMENT_BODY','Yorum');
	define('COMMENT_DATE','Yorum Tarihi');
	define('COMMENT_ACTIONS','Aksiyonlar');
	define('SHOW_FF_COMMENTS','FF Yorumlarını Göster');
	define('NO_FF_COMMENTS','Hiç Yorum Bulunmuyor');
	define('YOUR_FF_ITEMS','FriendFeed Ögeleriniz');
	define('FF_SAVE','Kaydet');
	define('FF_DELETE','Sil');
	define('ARE_YOU_SURE','Emin Misin?');
	define('FF_SEND_ADMIN_COMMENT',"Site yöneticilerinin yaptığı yorumlar FriendFeed'e yorum olarak eklensin");
	define('SHOW_OTHER_LIKES','ve %d Kullanıcı Daha');
?>